repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length", "120"]
        language_version: 3.11
  - repo:  https://github.com/PyCQA/flake8
    rev: v4.4.0
    hooks:
      - id: flake8
