version: '3.9'

services:
  spark:
    build: .
    volumes:
      - ./.jupyter:/root/.jupyter
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
        #      - PYSPARK_SUBMIT_ARGS=--packages io.delta:delta-core_2.12:1.2.1,org.apache.spark:spark-avro_2.12:2.4.4 pyspark-shell
    ports:
      - '8080:8080'
      - '7077:7077'
      - '8888:8888'

  spark-worker:
    build: .
    volumes:
      - ./.jupyter:/root/.jupyter
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
        #      - PYSPARK_SUBMIT_ARGS=--packages io.delta:delta-core_2.12:1.2.1,org.apache.spark:spark-avro_2.12:2.4.4 pyspark-shell
    ports:
      - '8889:8888'
        #    command: /bin/bash -c "while sleep 1000; do :; done"
